version: '3.8'

services:
  users-subgraph:
    build:
      context: ./subgraphs/users
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production

  products-subgraph:
    build:
      context: ./subgraphs/products
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production

  apollo-router:
    image: ghcr.io/apollographql/router:v1.33.0
    ports:
      - "4000:4000"
    volumes:
      - ./router/router.yaml:/dist/config/router.yaml
      - ./router/supergraph.graphql:/dist/schema/supergraph.graphql
    command: ["--config", "/dist/config/router.yaml", "--supergraph", "/dist/schema/supergraph.graphql"]
    depends_on:
      - users-subgraph
      - products-subgraph
    environment:
      - APOLLO_ROUTER_LOG=info